name: CI
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    name: Elixir ${{ matrix.elixir }} / OTP ${{ matrix.otp }}
    strategy:
      matrix:
        otp: ['26', '27']
        elixir: ['1.17', '1.18']
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Elixir and Erlang versions
        uses: erlef/setup-beam@v1
        id: setup-elixir
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}

      - name: Restore the cache
        uses: actions/cache@v3
        with:
          path: |
            deps
            _build
            priv/plts
          key: deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            deps-${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}

      - name: Run CI
        run: |
          mix ci
